steps:
  - group: ":chef: :sandwich: Build sandwich"
    key: "build"
    steps:
      - label: ":egg: Boil egg"
        command: "exit 0"

      - label: ":leafy_green: Chop lettuce "
        command: "exit 0"

      - label: ":butter: Butter bread"
        command: "exit 0"

  - label: ":point_right: :sandwich: Test sandwich"
    key: "test"
    depends_on: "build"
    command: "exit 0"

  - label: ":partyparrot: Eat sandwich"
    key: "deploy"
    depends_on: "test"
    command: "exit 0"
